apiVersion: v2
appVersion: "1.0"
description: A Helm chart for adoption-cos-api App
name: adoption-cos-api
home: https://github.com/hmcts/adoption-cos-api
version: 0.0.1
maintainers:
  - name: HMCTS Adoption team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
