tags:
  ccd-idam-pr: true

java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    CASE_DATA_STORE_BASEURL: "http://ccd-data-store-api-adoption-cos-api-pr-${CHANGE_ID}.service.core-compute-preview.internal"

idam-pr:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
  redirect_uris:
    CCD Admin:
      - https://admin-web-${SERVICE_FQDN}/oauth2redirect
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback
      - http://xui-${SERVICE_FQDN}/oauth2/callback

ccd:
  ccd:
    definitionImporter:
      enabled: false
    apiGatewayWeb:
      enabled: true
    s2s:
      enabled: false

  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
